db:
  image: mongo
  ports:
    - "27017:27017"
import:
  image: mongo
  volumes:
    - ./doc:/doc
  links: 
    - db
  working_dir: /doc
  command: "sh mongoImport.sh"  
web:
  image: youngdi/takeover:latest
  ports:
    - "8083:8083"
    - "8084:8084"
  links:
    - db
  environment:
    PORT: 8083 # this is optional, allows express to use process.env.PORT instead of a raw 3000
    mongoConfig: mongodb://db:27017/takeitover