# db:
#   image: mongo
#   ports:
#     - "27017:27017"
# import:
#   image: mongo
#   volumes:
#     - ./doc:/doc
#   links: 
#     - db
#   working_dir: /doc
#   command: "sh mongoImport.sh"  
# web:
#   image: youngdi/takeover:0.4
#   restart: always
#   ports:
#     - "8083:8083"
#     - "8084:8084"
#   links:
#     - db
#   environment:
#     PORT: 8083 # this is optional, allows express to use process.env.PORT instead of a raw 3000
#     mongoConfig: mongodb://db:27017/takeitover
#     dns: 'https://www.team4taiwan.com'
#     dnsPort: 443

version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
  db:
    image: mongo
    ports:
      - "27017:27017"
  import:
    image: mongo
    volumes:
      - ./doc:/doc
    links: 
      - db
    working_dir: /doc
    command: "sh mongoImport.sh"
  web:
    restart: always
    image: youngdi/takeover:0.4
    container_name: website
    volumes:
      - "./volumes/nginx-sample-website/conf.d/:/etc/nginx/conf.d"
      - "./volumes/config/sample-website/config.js:/usr/share/nginx/html/config.js"
    environment:
      PORT: 8083 # this is optional, allows express to use process.env.PORT instead of a raw 3000
      mongoConfig: mongodb://db:27017/takeitover
      dns: 'https://www.team4taiwan.com'
      dnsPort: 443
      - VIRTUAL_HOST=www.team4taiwan.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8083
      - LETSENCRYPT_HOST=www.team4taiwan.com
      - LETSENCRYPT_EMAIL=u9951062@gmail.com

